# Generated by Django 6.0.3 on 2026-03-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamation_numero_4d_reclamation_numero_8d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='imputation',
            field=models.CharField(choices=[('CIM', 'CIM'), ('CIB', 'CIB'), ('CLIENT', 'CLIENT'), ('ALERTE', 'ALERTE')], default='CIM', max_length=20, verbose_name='Imputation'),
        ),
        migrations.CreateModel(
            name='HuitD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_8d', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° 8D')),
                ('d0_date', models.DateField(blank=True, null=True, verbose_name='Date de démarrage')),
                ('d0_equipe', models.TextField(blank=True, help_text="Membres de l'équipe", verbose_name='Équipe 8D')),
                ('d1_leader', models.CharField(blank=True, max_length=100, verbose_name="Chef d'équipe")),
                ('d1_membres', models.TextField(blank=True, verbose_name="Membres de l'équipe")),
                ('d1_competences', models.TextField(blank=True, verbose_name='Compétences requises')),
                ('d2_description', models.TextField(blank=True, verbose_name='Description du problème')),
                ('d2_impact', models.TextField(blank=True, verbose_name='Impact client / interne')),
                ('d2_quantification', models.TextField(blank=True, verbose_name='Quantification (données)')),
                ('d2_historique', models.TextField(blank=True, verbose_name='Historique du problème')),
                ('d3_actions', models.TextField(blank=True, verbose_name='Actions immédiates')),
                ('d3_responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('d3_date', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('d3_efficacite', models.TextField(blank=True, verbose_name='Efficacité des actions')),
                ('d4_causes', models.TextField(blank=True, verbose_name='Causes racines identifiées')),
                ('d4_methodes', models.TextField(blank=True, verbose_name="Méthodes d'analyse utilisées")),
                ('d4_validation', models.TextField(blank=True, verbose_name='Validation des causes')),
                ('d5_actions', models.TextField(blank=True, verbose_name='Actions correctives')),
                ('d5_responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('d5_date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('d5_date_reelle', models.DateField(blank=True, null=True, verbose_name='Date réalisée')),
                ('d5_validation', models.TextField(blank=True, verbose_name='Validation des actions')),
                ('d6_actions', models.TextField(blank=True, verbose_name='Actions préventives')),
                ('d6_responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('d6_date', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('d6_standardisation', models.TextField(blank=True, verbose_name='Standardisation')),
                ('d7_actions', models.TextField(blank=True, verbose_name='Actions de prévention')),
                ('d7_documentation', models.TextField(blank=True, verbose_name='Documentation mise à jour')),
                ('d7_formation', models.TextField(blank=True, verbose_name='Formation réalisée')),
                ('d8_equipe', models.TextField(blank=True, verbose_name="Reconnaissance de l'équipe")),
                ('d8_retour', models.TextField(blank=True, verbose_name="Retour d'expérience")),
                ('d8_amelioration', models.TextField(blank=True, verbose_name='Améliorations identifiées')),
                ('etat', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=20, verbose_name='État')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('valide_par', models.CharField(blank=True, max_length=100, verbose_name='Validé par')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='huitd', to='reclamations.reclamation')),
            ],
            options={
                'verbose_name': 'Démarche 8D',
                'verbose_name_plural': 'Démarches 8D',
            },
        ),
    ]
