# Generated by Django 6.0.3 on 2026-04-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_alter_reclamation_imputation_huitd'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_of', models.CharField(max_length=50, unique=True, verbose_name='N° OF')),
                ('date_creation', models.DateField(verbose_name='Date création OF')),
                ('date_previsionnelle', models.DateField(blank=True, null=True, verbose_name='Date prévisionnelle fin')),
                ('date_reelle_fin', models.DateField(blank=True, null=True, verbose_name='Date réelle fin')),
                ('statut', models.CharField(choices=[('CREEE', 'Créé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='CREEE', max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable OF')),
                ('atelier', models.CharField(blank=True, max_length=100, verbose_name='Atelier')),
                ('priorite', models.IntegerField(choices=[(1, 'Haute'), (2, 'Moyenne'), (3, 'Basse')], default=3, verbose_name='Priorité')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordre de fabrication',
                'verbose_name_plural': 'Ordres de fabrication',
                'ordering': ['-date_creation', '-priorite'],
                'indexes': [models.Index(fields=['statut', 'date_creation'], name='reclamation_statut_c7c437_idx'), models.Index(fields=['numero_of'], name='reclamation_numero__1ff0aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='LigneOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prevue', models.IntegerField(default=0)),
                ('quantite_produite', models.IntegerField(default=0)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_of', to='reclamations.produit')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='reclamations.ordrefabrication')),
            ],
            options={
                'verbose_name': 'Ligne OF',
                'verbose_name_plural': 'Lignes OF',
                'unique_together': {('ordre_fabrication', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='AlerteFAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('ALERTE', 'Alerte'), ('URGENT', 'Urgent'), ('CRITIQUE', 'Critique')], default='ALERTE', max_length=20)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours'), ('TRAITEE', 'Traitée'), ('IGNOREE', 'Ignorée')], default='NOUVELLE', max_length=20)),
                ('derniere_production', models.DateField(blank=True, null=True, verbose_name='Date dernière production')),
                ('derniere_inspection', models.DateField(blank=True, null=True, verbose_name='Date dernière inspection FAI')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name='Date expiration FAI')),
                ('message', models.TextField()),
                ('commentaire', models.TextField(blank=True)),
                ('traite_par', models.CharField(blank=True, max_length=200)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_fai', to='reclamations.produit')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_fai', to='reclamations.ordrefabrication')),
            ],
            options={
                'verbose_name': 'Alerte FAI',
                'verbose_name_plural': 'Alertes FAI',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut', 'niveau'], name='reclamation_statut_183ac6_idx'), models.Index(fields=['ordre_fabrication', 'produit'], name='reclamation_ordre_f_c5f77f_idx')],
            },
        ),
    ]
