# Generated by Django 6.0.3 on 2026-04-10 07:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0004_ordrefabrication_ligneof_alertefai'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description de la non-conformité')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité concernée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ligne_reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformites', to='reclamations.lignereclamation')),
            ],
            options={
                'verbose_name': 'Non-conformité',
                'verbose_name_plural': 'Non-conformités',
                'ordering': ['-date_creation'],
            },
        ),
    ]
