# Generated by Django 6.0.3 on 2026-04-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0005_nonconformite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignereclamation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_reclamation', to='reclamations.site'),
        ),
    ]
