# Generated by Django 6.0.3 on 2026-04-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0006_lignereclamation_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='site',
        ),
    ]
