# Generated by Django 6.0.3 on 2026-04-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0007_remove_reclamation_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_of', models.CharField(blank=True, max_length=50, verbose_name='N° OF')),
                ('derniere_production', models.DateField(blank=True, null=True, verbose_name='Date dernière production')),
                ('statut', models.CharField(choices=[('INFO', 'Information'), ('ALERTE', 'Alerte'), ('URGENT', 'Urgent'), ('CRITIQUE', 'Critique')], default='INFO', max_length=20)),
                ('date_analyse', models.DateField(auto_now=True, verbose_name="Date d'analyse")),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Article FAI',
                'verbose_name_plural': 'Articles FAI',
                'ordering': ['-derniere_production'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueImportFAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('fichier_nom', models.CharField(max_length=255)),
                ('lignes_importees', models.IntegerField()),
                ('lignes_modifiees', models.IntegerField()),
                ('erreurs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historique import FAI',
                'verbose_name_plural': 'Historiques import FAI',
                'ordering': ['-date_import'],
            },
        ),
        migrations.RemoveIndex(
            model_name='alertefai',
            name='reclamation_statut_183ac6_idx',
        ),
        migrations.RemoveIndex(
            model_name='alertefai',
            name='reclamation_ordre_f_c5f77f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ligneof',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ligneof',
            name='ordre_fabrication',
        ),
        migrations.RemoveField(
            model_name='ligneof',
            name='produit',
        ),
        migrations.RemoveIndex(
            model_name='ordrefabrication',
            name='reclamation_statut_c7c437_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordrefabrication',
            name='reclamation_numero__1ff0aa_idx',
        ),
        migrations.AddField(
            model_name='articlefai',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fai_article', to='reclamations.produit'),
        ),
        migrations.RemoveField(
            model_name='alertefai',
            name='ordre_fabrication',
        ),
        migrations.RemoveField(
            model_name='alertefai',
            name='produit',
        ),
        migrations.DeleteModel(
            name='LigneOF',
        ),
        migrations.DeleteModel(
            name='OrdreFabrication',
        ),
        migrations.DeleteModel(
            name='AlerteFAI',
        ),
    ]
