# Generated by Django 6.0.3 on 2026-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0008_articlefai_historiqueimportfai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='imputation',
            field=models.CharField(choices=[('Vérification Encours', 'Vérification Encours'), ('CIM', 'CIM'), ('CIB', 'CIB'), ('CLIENT', 'CLIENT'), ('ALERTE', 'ALERTE'), ('KTN', 'KTN')], default='CIM', max_length=20, verbose_name='Imputation'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='type_nc',
            field=models.CharField(choices=[('FOURNISSEUR', 'Fournisseur'), ('LOGISTIQUE', 'Logistique'), ('TRANSPORT', 'Transport'), ('TECHNIQUE', 'Technique'), ('Stockage', 'Stockage')], default='TECHNIQUE', max_length=20, verbose_name='Type NC'),
        ),
    ]
