# Generated by Django 6.0.3 on 2026-04-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0009_alter_reclamation_imputation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huitd',
            name='d3_actions',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d3_date',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d3_efficacite',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d3_responsable',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d5_actions',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d5_date_prevue',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d5_date_reelle',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d5_responsable',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d5_validation',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d6_actions',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d6_date',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d6_responsable',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d6_standardisation',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d7_actions',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d7_documentation',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='d7_formation',
        ),
        migrations.AlterField(
            model_name='huitd',
            name='etat',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=20, verbose_name='État'),
        ),
        migrations.CreateModel(
            name='Action8D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('D3', 'D3 - Actions immédiates'), ('D5', 'D5 - Actions correctives'), ('D6', 'D6 - Actions préventives'), ('D7', 'D7 - Prévention récurrence')], max_length=2, verbose_name='Étape 8D')),
                ('ordre', models.IntegerField(default=1, verbose_name='Ordre')),
                ('action', models.TextField(verbose_name='Action')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('date_reelle', models.DateField(blank=True, null=True, verbose_name='Date réalisée')),
                ('efficacite', models.CharField(choices=[('EFFICACE', 'Efficace'), ('PARTIEL', 'Partiellement efficace'), ('INEFFICACE', 'Inefficace'), ('NON_EVALUE', 'Non évaluée')], default='NON_EVALUE', max_length=20, verbose_name='Efficacité')),
                ('commentaire_efficacite', models.TextField(blank=True, verbose_name="Commentaire sur l'efficacité")),
                ('date_evaluation', models.DateField(blank=True, null=True, verbose_name="Date d'évaluation")),
                ('indicateur_avant', models.CharField(blank=True, max_length=100, verbose_name='Indicateur avant')),
                ('valeur_avant', models.CharField(blank=True, max_length=50, verbose_name='Valeur avant')),
                ('indicateur_apres', models.CharField(blank=True, max_length=100, verbose_name='Indicateur après')),
                ('valeur_apres', models.CharField(blank=True, max_length=50, verbose_name='Valeur après')),
                ('realisee', models.BooleanField(default=False, verbose_name='Réalisée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('huitd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reclamations.huitd')),
            ],
            options={
                'verbose_name': 'Action 8D',
                'verbose_name_plural': 'Actions 8D',
                'ordering': ['etape', 'ordre'],
            },
        ),
    ]
