# Generated by Django 6.0.3 on 2026-04-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0010_remove_huitd_d3_actions_remove_huitd_d3_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action8d',
            name='commentaire_efficacite',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='date_evaluation',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='date_prevue',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='date_reelle',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='efficacite',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='indicateur_apres',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='indicateur_avant',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='realisee',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='valeur_apres',
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='valeur_avant',
        ),
        migrations.AddField(
            model_name='action8d',
            name='cause_racine_liee',
            field=models.TextField(blank=True, verbose_name='Cause racine associée'),
        ),
        migrations.AlterField(
            model_name='action8d',
            name='action',
            field=models.TextField(verbose_name='Action proposée'),
        ),
        migrations.CreateModel(
            name='PlanActionPDCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'action")),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('categorie', models.CharField(choices=[('QUALITE', 'Qualité'), ('PROCESS', 'Process'), ('FORMATION', 'Formation'), ('MAINTENANCE', 'Maintenance'), ('FOURNISSEUR', 'Fournisseur'), ('DOCUMENTATION', 'Documentation'), ('CONTROLE', 'Contrôle'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('date_cible', models.DateField(verbose_name='Date cible')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date réalisation')),
                ('priorite', models.CharField(choices=[('CRITIQUE', '🔴 Critique'), ('ELEVEE', '🟠 Élevée'), ('MOYENNE', '🟡 Moyenne'), ('BASSE', '🟢 Basse')], default='MOYENNE', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('PLAN', 'Planifié'), ('DO', 'En cours'), ('CHECK', 'En vérification'), ('ACT', 'Standardisé'), ('CLOTURE', 'Clôturé')], default='PLAN', max_length=20, verbose_name='Statut PDCA')),
                ('pourcentage_avancement', models.IntegerField(default=0, verbose_name='% Avancement')),
                ('efficacite', models.CharField(choices=[('EFFICACE', 'Efficace'), ('PARTIEL', 'Partiellement efficace'), ('INEFFICACE', 'Inefficace'), ('NON_EVALUE', 'Non évaluée')], default='NON_EVALUE', max_length=20, verbose_name='Efficacité')),
                ('commentaire_efficacite', models.TextField(blank=True, verbose_name="Commentaire sur l'efficacité")),
                ('date_evaluation', models.DateField(blank=True, null=True, verbose_name="Date d'évaluation")),
                ('critere_succes', models.TextField(blank=True, verbose_name='Critères de succès')),
                ('indicateur_avant', models.CharField(blank=True, max_length=100, verbose_name='Indicateur avant')),
                ('valeur_avant', models.CharField(blank=True, max_length=50, verbose_name='Valeur avant')),
                ('indicateur_apres', models.CharField(blank=True, max_length=100, verbose_name='Indicateur après')),
                ('valeur_apres', models.CharField(blank=True, max_length=50, verbose_name='Valeur après')),
                ('resultat_obtenu', models.TextField(blank=True, verbose_name='Résultat obtenu')),
                ('ecart', models.TextField(blank=True, verbose_name='Écart / Ajustements')),
                ('document_modifie', models.CharField(blank=True, max_length=200, verbose_name='Document modifié')),
                ('formation_realisee', models.BooleanField(default=False, verbose_name='Formation réalisée')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('blocage', models.TextField(blank=True, verbose_name='Points de blocage')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('action_8d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdca_actions', to='reclamations.action8d')),
                ('huitd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdca_actions', to='reclamations.huitd')),
            ],
            options={
                'verbose_name': 'Action PDCA',
                'verbose_name_plural': 'Actions PDCA',
                'ordering': ['priorite', 'date_cible'],
            },
        ),
    ]
