# Generated by Django 6.0.3 on 2026-04-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0011_remove_action8d_commentaire_efficacite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planactionpdca',
            name='action_8d',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='reclamation',
        ),
        migrations.RemoveField(
            model_name='planactionpdca',
            name='huitd',
        ),
        migrations.CreateModel(
            name='AnalyseNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_racine', models.TextField(blank=True, verbose_name='Cause racine identifiée')),
                ('methode_analyse', models.CharField(blank=True, choices=[('5P', '5 Pourquoi'), ('ISHIKAWA', 'Ishikawa'), ('PARETO', 'Pareto'), ('AUTRE', 'Autre')], max_length=50, verbose_name="Méthode d'analyse")),
                ('actions_proposees', models.TextField(blank=True, help_text='Actions qui seront suivies dans le PDCA', verbose_name='Actions proposées')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A_FAIRE', max_length=20, verbose_name="Statut de l'analyse")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('non_conformite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='reclamations.nonconformite')),
            ],
            options={
                'verbose_name': 'Analyse NC',
                'verbose_name_plural': 'Analyses NC',
            },
        ),
        migrations.CreateModel(
            name='ActionPDCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'action")),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('categorie', models.CharField(choices=[('QUALITE', 'Qualité'), ('PROCESS', 'Process'), ('FORMATION', 'Formation'), ('MAINTENANCE', 'Maintenance'), ('FOURNISSEUR', 'Fournisseur'), ('DOCUMENTATION', 'Documentation'), ('CONTROLE', 'Contrôle'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('date_cible', models.DateField(verbose_name='Date cible')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date réalisation')),
                ('priorite', models.CharField(choices=[('CRITIQUE', '🔴 Critique'), ('ELEVEE', '🟠 Élevée'), ('MOYENNE', '🟡 Moyenne'), ('BASSE', '🟢 Basse')], default='MOYENNE', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('PLAN', 'Planifié'), ('DO', 'En cours'), ('CHECK', 'En vérification'), ('ACT', 'Standardisé'), ('CLOTURE', 'Clôturé')], default='PLAN', max_length=20, verbose_name='Statut PDCA')),
                ('pourcentage_avancement', models.IntegerField(default=0, verbose_name='% Avancement')),
                ('efficacite', models.CharField(choices=[('EFFICACE', 'Efficace'), ('PARTIEL', 'Partiellement efficace'), ('INEFFICACE', 'Inefficace'), ('NON_EVALUE', 'Non évaluée')], default='NON_EVALUE', max_length=20, verbose_name='Efficacité')),
                ('commentaire_efficacite', models.TextField(blank=True, verbose_name="Commentaire sur l'efficacité")),
                ('date_evaluation', models.DateField(blank=True, null=True, verbose_name="Date d'évaluation")),
                ('critere_succes', models.TextField(blank=True, verbose_name='Critères de succès')),
                ('indicateur_avant', models.CharField(blank=True, max_length=100, verbose_name='Indicateur avant')),
                ('valeur_avant', models.CharField(blank=True, max_length=50, verbose_name='Valeur avant')),
                ('indicateur_apres', models.CharField(blank=True, max_length=100, verbose_name='Indicateur après')),
                ('valeur_apres', models.CharField(blank=True, max_length=50, verbose_name='Valeur après')),
                ('resultat_obtenu', models.TextField(blank=True, verbose_name='Résultat obtenu')),
                ('document_modifie', models.CharField(blank=True, max_length=200, verbose_name='Document modifié')),
                ('formation_realisee', models.BooleanField(default=False, verbose_name='Formation réalisée')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('blocage', models.TextField(blank=True, verbose_name='Points de blocage')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('analyse_nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_pdca', to='reclamations.analysenc')),
            ],
            options={
                'verbose_name': 'Action PDCA',
                'verbose_name_plural': 'Actions PDCA',
                'ordering': ['priorite', 'date_cible'],
            },
        ),
        migrations.DeleteModel(
            name='Action8D',
        ),
        migrations.DeleteModel(
            name='HuitD',
        ),
        migrations.DeleteModel(
            name='PlanActionPDCA',
        ),
    ]
