# Generated by Django 6.0.3 on 2026-05-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0013_huitd_facteurhumain_evidence8d_cinqw2h_cinqp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracterisationdefaut',
            name='huitd',
        ),
        migrations.RemoveField(
            model_name='cinqp',
            name='huitd',
        ),
        migrations.RemoveField(
            model_name='facteurishikawa',
            name='ishikawa',
        ),
        migrations.RemoveField(
            model_name='ishikawa',
            name='huitd',
        ),
        migrations.AlterModelOptions(
            name='cinqw2h',
            options={'verbose_name': '5W2H', 'verbose_name_plural': '5W2H'},
        ),
        migrations.AlterModelOptions(
            name='facteurhumain',
            options={'verbose_name': 'Facteur Humain', 'verbose_name_plural': 'Facteurs Humains'},
        ),
        migrations.AlterModelOptions(
            name='vrs',
            options={'verbose_name': 'VRS', 'verbose_name_plural': 'VRS'},
        ),
        migrations.RemoveField(
            model_name='action8d',
            name='delai',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='autres_clients_defaut',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='autres_clients_livres',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='combien',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='defauts_ecartes',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='dernier_cas',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='detection_attendue',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='impact_logistique',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='ou',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='ou_cree',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='pourquoi_probleme',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='probleme_connu',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='quand',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='quand_genere',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='qui',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='quoi',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='reinjection',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='rework',
        ),
        migrations.RemoveField(
            model_name='cinqw2h',
            name='symptomes',
        ),
        migrations.RemoveField(
            model_name='facteurhumain',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='facteurhumain',
            name='analyse',
        ),
        migrations.RemoveField(
            model_name='facteurhumain',
            name='description',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='numero_8d',
        ),
        migrations.RemoveField(
            model_name='huitd',
            name='transversalisation',
        ),
        migrations.AddField(
            model_name='action8d',
            name='delai_semaines',
            field=models.CharField(blank=True, max_length=50, verbose_name='Délai/Deadline'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_how_detected',
            field=models.TextField(blank=True, verbose_name='How was it detected? / Comment a-t-il été détecté ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_how_many',
            field=models.TextField(blank=True, verbose_name='How many were detected? / Combien de cas ont été détectés ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_logistic_impact',
            field=models.TextField(blank=True, verbose_name="What is the logistic impact on the customer ? / Quel est l'impact logistique sur le client ?"),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_other_customers_defect',
            field=models.TextField(blank=True, verbose_name="Was the defect reported by other customers ? / Le défaut a-t-il été rapporté par d'autres clients ?"),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_other_customers_delivered',
            field=models.TextField(blank=True, verbose_name='Was the product delivered to other customer ? / A quels autres Client le produit a-t-il été livré ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_what_happened',
            field=models.TextField(blank=True, verbose_name="What happened ? / Que s'est-il passé ?"),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_when_detected',
            field=models.TextField(blank=True, verbose_name='When did it happen? / Quand a-t-il été détecté ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_where_detected',
            field=models.TextField(blank=True, verbose_name='Where was it detected? / Où a-t-il été détecté ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_who_detected',
            field=models.TextField(blank=True, verbose_name='Who detected it? / Qui a détecté le problème ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='c_why_problem',
            field=models.TextField(blank=True, verbose_name='Why is it a problem ? / Pourquoi est-ce un problème ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='h_defects_ruled_out',
            field=models.TextField(blank=True, verbose_name="Which defects can be crossed out straightaway ? / Quel type de défaut peut être écarté d'emblée ?"),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='h_detection_expected',
            field=models.TextField(blank=True, verbose_name='At which operation should the problem have been detected ? / A quel stade le défaut est-il censé être détecté ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='h_known_problem',
            field=models.TextField(blank=True, verbose_name='Is the non conformity a known problem, a recurrent problem, internally and/or externally ? / La non-conformité est-elle connue, récurrente en externe ou en interne ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='h_last_reported',
            field=models.TextField(blank=True, verbose_name='When was the last reported problem? / A quelle date remonte le dernier cas ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='h_reinjection',
            field=models.TextField(blank=True, verbose_name='Are we capturing the defect when reinjecting products in the normal process ? / Le produit non conforme ré-introduit dans le processus est-il détecté par celui-ci ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='h_rework',
            field=models.TextField(blank=True, verbose_name="Are the bad parts from a reworked process? / Les pièces mauvaises sont-elles issues d'une gamme rework ?"),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='h_symptoms',
            field=models.TextField(blank=True, verbose_name="What are the symptoms ? / De quoi s'agit-il ?"),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='h_when_generated',
            field=models.TextField(blank=True, verbose_name='When was the problem internally generated ? / Quand le problème a-t-il été généré en interne ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='h_where_created',
            field=models.TextField(blank=True, verbose_name='Where was the defect created amongst the operations ? / Où le défaut a-t-il pu être créé ?'),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='suivi',
            field=models.CharField(blank=True, default='PR-SM-06', max_length=50, verbose_name='Suivant'),
        ),
        migrations.AddField(
            model_name='facteurhumain',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='facteurhumain',
            name='designation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='facteurhumain',
            name='nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom / Name'),
        ),
        migrations.AddField(
            model_name='facteurhumain',
            name='site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='facteurhumain',
            name='suivi',
            field=models.CharField(blank=True, default='PR-SM-06', max_length=50, verbose_name='Suivant'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='animateur_fonction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fonction animateur'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_caracterisation',
            field=models.TextField(blank=True, verbose_name='Caractérisation du défaut / Characterization of the defect'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_combien',
            field=models.TextField(blank=True, verbose_name='Combien ? / How much ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_comment',
            field=models.TextField(blank=True, verbose_name='Comment ? / How ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_illustration_conforme',
            field=models.ImageField(blank=True, upload_to='8d/d1/', verbose_name='Illustration produit conforme'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_illustration_defectueux',
            field=models.ImageField(blank=True, upload_to='8d/d1/', verbose_name='Illustration produit défectueux'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_ou',
            field=models.TextField(blank=True, verbose_name='Où ? / Where ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_pourquoi',
            field=models.TextField(blank=True, verbose_name='Pourquoi ? / Why ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_probleme_connu',
            field=models.BooleanField(default=False, verbose_name='Le problème est-il déjà connu ? / Is the problem already known?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_quand',
            field=models.TextField(blank=True, verbose_name='Quand ? / When ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_qui',
            field=models.TextField(blank=True, verbose_name='Qui ? / Who ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_quoi',
            field=models.TextField(blank=True, verbose_name='Quoi ? / What ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_risque',
            field=models.BooleanField(default=False, verbose_name='Risque sur produit/process similaire ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d1_risque_detail',
            field=models.TextField(blank=True, verbose_name='Si oui, sur lequel ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d2_actions',
            field=models.TextField(blank=True, verbose_name='Actions envisagées pour éviter la non détection'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d2_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date D2'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d2_of_concernes',
            field=models.TextField(blank=True, verbose_name='OF concernés / OF concerned'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d2_quantite_rebutee',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Qté rebutée / Scrap Qty'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d2_quantite_retoucher',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Qté à retoucher / Qty to be reworked'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d2_tri',
            field=models.BooleanField(default=False, verbose_name='Un tri est-il nécessaire ? / Is sorting necessary?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d3_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date D3'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d4_causes_apparition',
            field=models.TextField(blank=True, verbose_name="Cause(s) probable(s) d'apparition du défaut ?"),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d4_causes_non_detection',
            field=models.TextField(blank=True, verbose_name='Cause(s) probable(s) de non détection ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d4_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date D4'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d5_causes_non_detection',
            field=models.TextField(blank=True, verbose_name='Causes racines de la non détection'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d5_causes_occurrence',
            field=models.TextField(blank=True, verbose_name="Causes racines de l'occurrence"),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d7_suffisant',
            field=models.TextField(blank=True, verbose_name='Ces actions sont-elles suffisantes pour éradiquer le problème ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d7_verification',
            field=models.TextField(blank=True, verbose_name="Comment est vérifié l'efficacité des actions (qui ? comment ?) ?"),
        ),
        migrations.AddField(
            model_name='huitd',
            name='d8_transversalisation',
            field=models.TextField(blank=True, verbose_name='Sur quels périmètres peut-on transversaliser les leçons apprises ?'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='date_maj',
            field=models.DateField(auto_now=True, verbose_name='Date MàJ'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='interne',
            field=models.CharField(blank=True, choices=[('QUALITE', 'Qualité / Quality'), ('PRODUCTION', 'Production'), ('CLIENT', 'Client / Customer'), ('FOURNISSEUR', 'Fournisseur / Supplier')], max_length=20, verbose_name='Interne / Internal'),
        ),
        migrations.AddField(
            model_name='huitd',
            name='pilote_fonction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fonction pilote'),
        ),
        migrations.AlterField(
            model_name='action8d',
            name='action',
            field=models.TextField(verbose_name='Actions : occurrence - non détection'),
        ),
        migrations.AlterField(
            model_name='action8d',
            name='numero_cause',
            field=models.CharField(blank=True, max_length=10, verbose_name='Causes retenues / Causes retained'),
        ),
        migrations.AlterField(
            model_name='action8d',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('REALISE', 'Réalisé'), ('EFFICACE', 'Efficace')], default='PLANIFIE', max_length=20, verbose_name='Statut / Status'),
        ),
        migrations.AlterField(
            model_name='action8d',
            name='type_action',
            field=models.CharField(choices=[('CORRECTIVE', 'AC - Action Corrective'), ('PREVENTIVE', 'AP - Action Préventive')], default='CORRECTIVE', max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='cinqw2h',
            name='nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom / Name'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='animateur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Animateur / Animator'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='date_ouverture',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'ouverture / Opening Date"),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='decision_8d',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='OUI', max_length=3, verbose_name='Engager un 8D ?'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='decision_hcim',
            field=models.CharField(blank=True, max_length=100, verbose_name='Non, exigé par / required by'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='designation_piece',
            field=models.CharField(blank=True, max_length=200, verbose_name='Désignation pièces / Parts Designation'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='fin_huitd',
            field=models.DateField(blank=True, null=True, verbose_name='Fin du 8D / Closure of 8D'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='fin_huitd_signature',
            field=models.CharField(blank=True, max_length=100, verbose_name='Date & Signature'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='huitd_accepte',
            field=models.BooleanField(default=False, verbose_name='8D accepté / 8D Report Accepted'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='lieu_detection',
            field=models.CharField(choices=[('QUALITE', 'Qualité / Quality'), ('PRODUCTION', 'Production'), ('CLIENT', 'Client / Customer'), ('FOURNISSEUR', 'Fournisseur / Supplier')], default='QUALITE', max_length=20, verbose_name='Lieu de détection / Detection Site'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='pilote',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pilote / Leader'),
        ),
        migrations.AlterField(
            model_name='participant8d',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fonction / Function'),
        ),
        migrations.AlterField(
            model_name='participant8d',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom / Name'),
        ),
        migrations.AlterField(
            model_name='participant8d',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rôle / Role'),
        ),
        migrations.AlterField(
            model_name='vrs',
            name='designation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='vrs',
            name='nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom / Name'),
        ),
        migrations.CreateModel(
            name='Alteration8D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=200, verbose_name='Alteration Necessary')),
                ('remarque', models.TextField(blank=True, verbose_name='Remark')),
                ('pilote', models.CharField(blank=True, max_length=100, verbose_name='Pilot')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('ordre', models.IntegerField(default=1, verbose_name='Ordre')),
                ('huitd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alterations', to='reclamations.huitd')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='CauseCinqP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cause', models.CharField(choices=[('OCCURRENCE', 'Occurrence'), ('NON_DETECTION', 'No Detection')], max_length=15, verbose_name='Type')),
                ('facteur_prouve', models.CharField(blank=True, max_length=10, verbose_name='Facteur prouvé / Proven factor')),
                ('pourquoi_1', models.TextField(blank=True, verbose_name='1. Pourquoi ? / Why?')),
                ('pourquoi_2', models.TextField(blank=True, verbose_name='2. Pourquoi ? / Why?')),
                ('pourquoi_3', models.TextField(blank=True, verbose_name='3. Pourquoi ? / Why?')),
                ('pourquoi_4', models.TextField(blank=True, verbose_name='4. Pourquoi ? / Why?')),
                ('pourquoi_5', models.TextField(blank=True, verbose_name='5. Pourquoi ? / Why?')),
                ('huitd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes_5p', to='reclamations.huitd')),
            ],
            options={
                'verbose_name': '5 Pourquoi',
                'verbose_name_plural': '5 Pourquoi',
                'ordering': ['type_cause', 'facteur_prouve'],
            },
        ),
        migrations.CreateModel(
            name='CauseIshikawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('A', 'A - Milieu / Environment'), ('B', 'B - Méthodes / Methods'), ('C', 'C - Moyens / Resources'), ('D', "D - Main d'œuvre / Personnel"), ('E', 'E - Matières / Materials'), ('F', 'F - Mesures / Measures')], max_length=1, verbose_name='Catégorie 6M')),
                ('cause', models.TextField(verbose_name='Facteur / Factor')),
                ('type_cause', models.CharField(choices=[('OCCURRENCE', 'Occurrence'), ('NON_DETECTION', 'No Detection')], default='OCCURRENCE', max_length=15, verbose_name='Type')),
                ('ordre', models.IntegerField(default=1, verbose_name='Ordre')),
                ('huitd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes_ishikawa', to='reclamations.huitd')),
            ],
            options={
                'verbose_name': 'Cause Ishikawa',
                'verbose_name_plural': 'Causes Ishikawa',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationFacteurHumain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Catégorie')),
                ('numero_critere', models.CharField(max_length=10, verbose_name='N° Critère')),
                ('critere', models.TextField(verbose_name='Criteria / Critères')),
                ('evaluation', models.CharField(blank=True, max_length=100, verbose_name='Evaluation')),
                ('commentaire', models.TextField(blank=True, verbose_name='Comments / Commentaires')),
                ('facteur_humain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='reclamations.facteurhumain')),
            ],
            options={
                'ordering': ['categorie', 'numero_critere'],
            },
        ),
        migrations.CreateModel(
            name='FacteurVRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('A', 'A - Milieu / Environment'), ('B', 'B - Méthodes / Methods'), ('C', 'C - Moyens / Resources'), ('D', "D - Main d'œuvre / Personnel"), ('E', 'E - Matières / Materials'), ('F', 'F - Mesures / Measures')], max_length=1, verbose_name='Catégorie 6M')),
                ('facteur_probable', models.TextField(blank=True, verbose_name='Facteur probable / Probable factor')),
                ('parametre_mesurable', models.TextField(blank=True, verbose_name='Paramètre mesurable / Is there a measurable parameter')),
                ('standard_exigence', models.TextField(blank=True, verbose_name='Standard ou exigences / What is the standard or requirement')),
                ('donnees_bonnes', models.TextField(blank=True, verbose_name='Données réelles (bonnes) / Real data (good parts)')),
                ('donnees_mauvaises', models.TextField(blank=True, verbose_name='Données réelles (mauvaises) / Real data (bad parts)')),
                ('standard_suivi', models.BooleanField(default=False, verbose_name='Standard suivi ? / Is the standard followed?')),
                ('standard_approprie', models.BooleanField(default=False, verbose_name='Standard approprié ? / Is the standard appropriate')),
                ('lien_prouve', models.BooleanField(default=False, verbose_name='Lien prouvé ? / Proven location')),
                ('facteur_prouve', models.BooleanField(default=False, verbose_name='Facteur prouvé / Proven factor')),
                ('vrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facteurs', to='reclamations.vrs')),
            ],
            options={
                'ordering': ['categorie'],
            },
        ),
        migrations.DeleteModel(
            name='AlterationNecessaire',
        ),
        migrations.DeleteModel(
            name='CaracterisationDefaut',
        ),
        migrations.DeleteModel(
            name='CinqP',
        ),
        migrations.DeleteModel(
            name='FacteurIshikawa',
        ),
        migrations.DeleteModel(
            name='Ishikawa',
        ),
    ]
