# Generated by Django 6.0.3 on 2026-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0014_remove_caracterisationdefaut_huitd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysenc',
            name='non_conformite',
        ),
        migrations.AlterModelOptions(
            name='evaluationfacteurhumain',
            options={'ordering': ['categorie', 'numero_critere'], 'verbose_name': 'Évaluation Facteur Humain', 'verbose_name_plural': 'Évaluations Facteurs Humains'},
        ),
        migrations.AlterModelOptions(
            name='facteurvrs',
            options={'ordering': ['categorie'], 'verbose_name': 'Facteur VRS', 'verbose_name_plural': 'Facteurs VRS'},
        ),
        migrations.RemoveField(
            model_name='facteurhumain',
            name='date',
        ),
        migrations.RemoveField(
            model_name='facteurhumain',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='facteurhumain',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='facteurhumain',
            name='site',
        ),
        migrations.RemoveField(
            model_name='facteurhumain',
            name='suivi',
        ),
        migrations.RemoveField(
            model_name='vrs',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vrs',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='vrs',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='vrs',
            name='site',
        ),
        migrations.AddField(
            model_name='causecinqp',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='causecinqp',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='causeishikawa',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='causeishikawa',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cinqw2h',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facteurhumain',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facteurhumain',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vrs',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vrs',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='action8d',
            name='numero_cause',
            field=models.CharField(blank=True, max_length=10, verbose_name='Causes retenues'),
        ),
        migrations.AlterField(
            model_name='articlefai',
            name='date_analyse',
            field=models.DateField(auto_now=True, null=True, verbose_name="Date d'analyse"),
        ),
        migrations.AlterField(
            model_name='causecinqp',
            name='type_cause',
            field=models.CharField(choices=[('OCCURRENCE', 'Occurrence'), ('NON_DETECTION', 'No Detection')], default='OCCURRENCE', max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='causeishikawa',
            name='cause',
            field=models.TextField(blank=True, verbose_name='Facteur / Factor'),
        ),
        migrations.AlterField(
            model_name='causeishikawa',
            name='type_cause',
            field=models.CharField(choices=[('OCCURRENCE', 'Occurrence'), ('NON_DETECTION', 'No Detection')], default='OCCURRENCE', max_length=15, verbose_name='Type de cause'),
        ),
        migrations.AlterField(
            model_name='evaluationfacteurhumain',
            name='categorie',
            field=models.CharField(choices=[('1', '1. Moyens et outils / Means and tools'), ('2', '2. Conditions de travail / Working conditions'), ('3', '3. Autres facteurs / Other factors')], max_length=1, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='evidence8d',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='categorie',
            field=models.CharField(choices=[('A', 'A - Milieu / Environment'), ('B', 'B - Méthodes / Methods'), ('C', 'C - Moyens / Resources'), ('E', 'E - Matières / Materials'), ('F', 'F - Mesures / Measures')], max_length=1, verbose_name='Catégorie 6M'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='d1_probleme_connu',
            field=models.BooleanField(default=False, verbose_name='Le problème est-il déjà connu ?'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='d2_of_concernes',
            field=models.TextField(blank=True, verbose_name='OF concernés'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='d2_tri',
            field=models.BooleanField(default=False, verbose_name='Un tri est-il nécessaire ?'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='d7_suffisant',
            field=models.TextField(blank=True, verbose_name='Ces actions sont-elles suffisantes ?'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='d7_verification',
            field=models.TextField(blank=True, verbose_name="Comment est vérifié l'efficacité des actions ?"),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='d8_transversalisation',
            field=models.TextField(blank=True, verbose_name='Sur quels périmètres peut-on transversaliser ?'),
        ),
        migrations.AlterField(
            model_name='huitd',
            name='date_maj',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date MàJ'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationfacteurhumain',
            unique_together={('facteur_humain', 'categorie', 'numero_critere')},
        ),
        migrations.AlterUniqueTogether(
            name='facteurvrs',
            unique_together={('vrs', 'categorie')},
        ),
        migrations.DeleteModel(
            name='ActionPDCA',
        ),
        migrations.DeleteModel(
            name='AnalyseNC',
        ),
    ]
