# Generated by Django 6.0.3 on 2026-05-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0015_remove_analysenc_non_conformite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action8d',
            options={'ordering': ['ordre'], 'verbose_name': 'Action 8D', 'verbose_name_plural': 'Actions 8D'},
        ),
        migrations.AddField(
            model_name='action8d',
            name='avancement',
            field=models.IntegerField(default=0, verbose_name='Avancement (%)'),
        ),
        migrations.AddField(
            model_name='action8d',
            name='comment_verification',
            field=models.TextField(blank=True, verbose_name='Comment ?'),
        ),
        migrations.AddField(
            model_name='action8d',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='action8d',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='action8d',
            name='date_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue'),
        ),
        migrations.AddField(
            model_name='action8d',
            name='date_realisee',
            field=models.DateField(blank=True, null=True, verbose_name='Date réalisée'),
        ),
        migrations.AddField(
            model_name='action8d',
            name='deploiement',
            field=models.TextField(blank=True, verbose_name='Déploiement'),
        ),
        migrations.AddField(
            model_name='action8d',
            name='remarque',
            field=models.TextField(blank=True, verbose_name='Remarque / Action suivante'),
        ),
        migrations.AddField(
            model_name='action8d',
            name='verification_efficacite',
            field=models.TextField(blank=True, verbose_name="Vérification de l'efficacité"),
        ),
        migrations.AlterField(
            model_name='action8d',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('REALISE', 'Réalisé'), ('EFFICACE', 'Efficace'), ('ABANDONNE', 'Abandonné')], default='PLANIFIE', max_length=20, verbose_name='Statut'),
        ),
    ]
