# Generated by Django 6.0.3 on 2026-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0016_alter_action8d_options_action8d_avancement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action8d',
            name='verification_efficacite',
        ),
        migrations.AddField(
            model_name='action8d',
            name='efficacite',
            field=models.CharField(choices=[('0', '0% - Aucune efficacité'), ('25', '25% - Très faible'), ('50', '50% - Partielle'), ('75', '75% - Bonne'), ('100', '100% - Très bonne / Complète')], default='0', max_length=3, verbose_name="Vérification de l'efficacité"),
        ),
        migrations.AlterField(
            model_name='action8d',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('REALISE', 'Réalisé'), ('ABANDONNE', 'Abandonné')], default='PLANIFIE', max_length=20, verbose_name='Statut'),
        ),
    ]
