# Generated by Django 6.0.3 on 2026-05-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0017_remove_action8d_verification_efficacite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignereclamation',
            name='description_non_conformite',
        ),
    ]
