# Generated by Django 6.0.3 on 2026-05-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0018_remove_lignereclamation_description_non_conformite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant8d',
            name='role',
        ),
    ]
