# Generated by Django 6.0.3 on 2026-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0019_remove_participant8d_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant8d',
            name='role',
            field=models.CharField(choices=[('Pilote / Leader', 'Pilote / Leader'), ('Animateur / Animator', 'Animateur / Animator'), ('Participant', 'Participant')], default='Participant', max_length=50, verbose_name='Role'),
        ),
    ]
