# Generated by Django 6.0.5 on 2026-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0020_participant8d_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant8d',
            name='role',
            field=models.CharField(choices=[('Participant', 'Participant')], default='Participant', max_length=50, verbose_name='Role'),
        ),
    ]
