# Generated by Django 6.0.5 on 2026-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0021_alter_participant8d_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facteurvrs',
            options={'ordering': ['categorie', 'ordre']},
        ),
        migrations.AlterUniqueTogether(
            name='facteurvrs',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='facteurvrs',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='categorie',
            field=models.CharField(choices=[('A', 'A - Milieu / Environment'), ('B', 'B - Méthodes / Methods'), ('C', 'C - Moyens / Resources'), ('D', "D - Main d'œuvre / Personnel"), ('E', 'E - Matières / Materials'), ('F', 'F - Mesures / Measures')], max_length=1),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='donnees_bonnes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='donnees_mauvaises',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='facteur_probable',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='facteur_prouve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='lien_prouve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='parametre_mesurable',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='standard_approprie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='standard_exigence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facteurvrs',
            name='standard_suivi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='facteurvrs',
            unique_together={('vrs', 'categorie', 'ordre')},
        ),
    ]
