# Generated by Django 6.0.5 on 2026-06-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0022_alter_facteurvrs_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facteurvrs',
            unique_together=set(),
        ),
    ]
