# Generated by Django 6.0.5 on 2026-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0023_alter_facteurvrs_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='besoin_4dp',
            field=models.BooleanField(default=False, help_text='Cocher si une démarche 4DP est nécessaire', verbose_name='4DP nécessaire ?'),
        ),
    ]
