# Generated by Django 6.0.5 on 2026-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0024_reclamation_besoin_4dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='huitd',
            name='numero_8d',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° 8D'),
        ),
    ]
