# Generated by Django 6.0.5 on 2026-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0025_huitd_numero_8d'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='huitd_non_applicable',
            field=models.BooleanField(default=False, verbose_name='8D non applicable'),
        ),
    ]
