# Generated by Django 6.0.5 on 2026-07-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0026_reclamation_huitd_non_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='verification_eficacite',
            field=models.BooleanField(default=False, verbose_name='Vérification efficacité'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='etat_4d',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=20, verbose_name='État 4D'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='etat_8d',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=20, verbose_name='État 8D'),
        ),
    ]
