# Generated by Django 6.0.5 on 2026-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_created_by_remove_user_temp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('quality_manager', 'Responsable Qualité Client'), ('quality_engineer', 'Ingénieur Qualité Client'), ('product_quality_engineer', 'Ingénieur Qualité Produit'), ('production_manager', 'Responsable Production'), ('quality_coordinator', 'Coordonnateur Qualité'), ('viewer', 'Consultant')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('quality_manager', 'Responsable Qualité Client'), ('quality_engineer', 'Ingénieur Qualité Client'), ('product_quality_engineer', 'Ingénieur Qualité Produit'), ('production_manager', 'Responsable Production'), ('quality_coordinator', 'Coordonnateur Qualité'), ('viewer', 'Consultant')], default='viewer', max_length=50),
        ),
    ]
